services:
  api:
    build: .
    container_name: chashforce_api
    ports:
      - 3000:3000
    working_dir: /app
    volumes:
      - .:/app
    command: "dev"
    env_file:
      - .env
    depends_on:
      database:
        condition: service_healthy
    networks:
      - cashforce_network

  database:
    image: mysql:latest
    container_name: chashforce_database
    ports:
      - 3306:3306
    env_file:
      - .env
    volumes:
      - mysql_data:/var/lib/mysql
      - ./src/database:/docker-entrypoint-initdb.d
    networks:
      - cashforce_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

networks:
  cashforce_network:
    driver: bridge

volumes:
  mysql_data: